version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  order-service:
    image: bselim/order-service:2.0.0
    container_name: order-service
    restart: always
    ports:
      - 9001:9001
    depends_on:
      - redis