apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: order-service
  labels:
    app.kubernetes.io/name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-service
    spec:
      containers:
        - name: redis
          image: redis:alpine # <--- Redis image
          ports:
            - containerPort: 6379
        - name: order-service
          image: bselim/order-service:latest # <--- Order service image
          ports:
            - containerPort: 9001 
