apiVersion: networking.k8s.io/v1 # This indicates the API version to use when creating this Kubernetes resource.

kind: Ingress # This tells Kubernetes that we are creating an Ingress resource.

metadata: # This block contains metadata about the Ingress.
  name: order-service-ingress # The name of the Ingress.
  namespace: order-service # The namespace in which the Ingress will be created.
  annotations: # Annotations are arbitrary non-identifying metadata.
    kubernetes.io/ingress.class: nginx # This annotation indicates that the NGINX Ingress controller should be used.
    nginx.ingress.kubernetes.io/rewrite-target: / # This annotation sets up URL rewriting, replacing the path matched by the regular expression in the path with the value specified here.

spec: # This block contains the specification of the Ingress.
  rules: # Each rule applies to a specific host (not included here, so applicable to any host) and a list of path patterns.
    - http: # This begins the definition of an HTTP rule.
        paths: # This is a list of paths that should match this rule.
          - path: / # This is a regular expression that matches any path starting with "/order/".
            pathType: Prefix # This indicates that the path should be interpreted as a prefix. If the request path starts with the specified path, then it matches.
            backend: # This block defines the backend service to which matching requests should be routed.
              service: # This specifies the specific service to use
                name: service-order-service # The name of the service to which requests should be routed.
                port: # This specifies the port on the service to use.
                  name: order-port # The name of the port on the service to use. The service must have a port with this name.

