apiVersion: v1
kind: Service
metadata:
  name: service-order-service
  namespace: order-service
spec:
  selector:
    app.kubernetes.io/name: order-service
  ports:
    - name: order-port
      protocol: TCP
      port: 9001 # <--- Order service port
